module.exports = {
  content: ["./dashboard.html", "./dashboard.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-high": "#2a2a2c",
          "inverse-primary": "#875200",
          "primary-fixed-dim": "#ffb867",
          "surface": "#131315",
          "inverse-surface": "#e5e1e4",
          "on-secondary": "#003824",
          "outline": "#a18d7a",
          "primary": "#ffc78b",
          "surface-dim": "#131315",
          "primary-fixed": "#ffddba",
          "on-primary-fixed": "#2b1700",
          "on-secondary-fixed-variant": "#005236",
          "on-error-container": "#ffdad6",
          "surface-container-highest": "#353437",
          "outline-variant": "#544434",
          "on-primary-container": "#683e00",
          "background": "#131315",
          "primary-container": "#ffa116",
          "secondary-fixed-dim": "#4edea3",
          "on-tertiary-fixed-variant": "#653e00",
          "surface-tint": "#ffb867",
          "secondary-fixed": "#6ffbbe",
          "on-tertiary-container": "#663f00",
          "secondary": "#4edea3",
          "on-surface": "#e5e1e4",
          "on-surface-variant": "#d9c3ad",
          "surface-container-lowest": "#0e0e10",
          "secondary-container": "#00a572",
          "on-tertiary": "#472a00",
          "on-error": "#690005",
          "surface-bright": "#39393b",
          "on-secondary-fixed": "#002113",
          "surface-variant": "#353437",
          "surface-container-low": "#1c1b1d",
          "tertiary-fixed-dim": "#ffb95f",
          "on-secondary-container": "#00311f",
          "inverse-on-surface": "#313032",
          "on-primary": "#482900",
          "surface-container": "#201f22",
          "on-tertiary-fixed": "#2a1700",
          "error": "#ffb4ab",
          "tertiary-fixed": "#ffddb8",
          "tertiary-container": "#fba315",
          "on-primary-fixed-variant": "#673d00",
          "tertiary": "#ffc886",
          "error-container": "#93000a",
          "on-background": "#e5e1e4"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "card-gap": "1rem",
          "gutter": "1.5rem",
          "section-margin": "4rem",
          "container-padding": "2rem",
          "unit": "4px"
      },
      "fontFamily": {
          "headline-lg": ["Geist", "sans-serif"],
          "stat-lg": ["Geist", "sans-serif"],
          "body-sm": ["Geist", "sans-serif"],
          "label-mono": ["JetBrains Mono", "monospace"],
          "headline-lg-mobile": ["Geist", "sans-serif"],
          "display": ["Geist", "sans-serif"],
          "headline-md": ["Geist", "sans-serif"],
          "body-lg": ["Geist", "sans-serif"]
      },
      "fontSize": {
          "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
          "stat-lg": ["36px", { "lineHeight": "1.0", "letterSpacing": "-0.05em", "fontWeight": "700" }],
          "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
          "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
          "headline-md": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
